export interface IPlace {
    id: string,
    name: string,
    description: string,
    category: string,
    companyId: string,
    address: string,
    coordinates: {
        lat: number,
        lon: number,
    },
}

export interface ICompany {
    id: string,
    name: string,
    logoUrl: string,
    description: string,
}

export const companies: ICompany[] = [
    {
        id: "1",
        name: "Motley Crew",
        logoUrl: "https://example.com/logos/motley-crew.png",
        description: "Motley Crew offers specialized fitness classes including CrossFit and personal training."
    },
    {
        id: "2",
        name: "Yoga Life",
        logoUrl: "https://example.com/logos/yoga-life.png",
        description: "Yoga Life is a premium yoga studio offering classes for all skill levels."
    },
    {
        id: "3",
        name: "Roark Gyms",
        logoUrl: "https://example.com/logos/roark.png",
        description: "Roark Gyms is known for high-intensity training programs and personalized coaching."
    },
    {
        id: "4",
        name: "DO Martial Arts",
        logoUrl: "https://example.com/logos/do-martial-arts.png",
        description: "DO Martial Arts specializes in Muay Thai, Brazilian Jiu-Jitsu, and self-defense."
    },
    {
        id: '5',
        name: 'McDonalds',
        logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/McDonald%27s_logo.svg',
        description: ''
    },
    {
        id: '6',
        name: 'KFC',
        logoUrl: 'https://blog.logomyway.com/wp-content/uploads/2020/09/KFC-logo.jpg',
        description: ''
    },
    {
        id: '7',
        name: "Nando's",
        logoUrl: 'https://d3faj0w6aqatyx.cloudfront.net/uploads/2016/01/22083950/logo-1002x596.jpg',
        description: ''
    },
    {
        id: '8',
        name: "The Test Kitchen",
        logoUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/04/8e/48/9a/the-test-kitchen.jpg',
        description: ''
    },
    {
        id: '9',
        name: "La Colombe",
        logoUrl: 'https://images.squarespace-cdn.com/content/v1/5fbf64bded5c1f23ba501ca6/1606379016990-43TH0ULWR5CFXQT4SCLM/LA+COLOMBE+LOGO+transparent.png',
        description: ''
    },
    {
        id: '24',
        name: "Shell",
        logoUrl: 'https://www.fleet.be/wp-content/uploads/2016/12/CMYK-Shell-Pecten.png',
        description: ''
    },
    {
        id: '25',
        name: "Engen",
        logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/26/Engen_Petroleum_Limited_Logo.jpg',
        description: ''
    },
    {
        id: '26',
        name: "BP",
        logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/BP_Helios_logo.svg/1200px-BP_Helios_logo.svg.png',
        description: ''
    },
    {
        id: '27',
        name: "Total",
        logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png',
        description: ''
    },
    {
        id: '28',
        name: "Caltex",
        logoUrl: 'https://seeklogo.com/images/C/Caltex-logo-0950A63C96-seeklogo.com.png',
        description: ''
    },
    {
        id: '29',
        name: "Sasol",
        logoUrl: 'https://pbs.twimg.com/profile_images/876689910643781634/2wPOIti3_400x400.jpg',
        description: ""
    },
    {
        id: '30',
        name: "Unknown",
        logoUrl: '',
        description: ""
    },
    {
        id: '31',
        name: "Unknown",
        logoUrl: '',
        description: ""
    },
    {
        id: "32",
        name: "The Table Bay Hotel",
        logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuwWcmjLD_5DKsm3FbsTyHnlJtAndAqkduEw&s",
        description: "Luxury hotel offering stunning views of Table Mountain and the V&A Waterfront.",
    },
    {
        id: "33",
        name: "One&Only Cape Town",
        logoUrl: "https://searchlogovector.com/wp-content/uploads/2019/01/oneandonly-resorts-logo-vector-xs.png",
        description: "Five-star hotel featuring world-class dining and a central location in the V&A Waterfront.",
    },
    {
        id: "34",
        name: "Belmond Mount Nelson Hotel",
        logoUrl: "https://example.com/mountnelson_logo.png",
        description: "Iconic pink hotel with a rich history and elegant settings.",
    },
    {
        id: "35",
        name: "Camps Bay Retreat",
        logoUrl: "https://example.com/campsbay_logo.png",
        description: "Boutique hotel nestled in the hills overlooking Camps Bay with luxurious amenities.",
    },
    {
        id: "36",
        name: "Radisson Blu Hotel Sandton",
        logoUrl: "https://example.com/radissonblu_logo.png",
        description: "Modern hotel offering premium comfort and convenience in Sandton, Johannesburg.",
    },
    {
        id: "37",
        name: "The Saxon Hotel, Villas & Spa",
        logoUrl: "https://example.com/saxon_logo.png",
        description: "Exclusive luxury retreat known for its tranquility and high-end services.",
    },
    {
        id: "38",
        name: "Protea Hotel Fire & Ice! by Marriott Pretoria Menlyn",
        logoUrl: "https://example.com/fireandice_logo.png",
        description: "Trendy hotel with a vibrant atmosphere, located in Pretoria's Menlyn area.",
    },
    {
        id: "39",
        name: "Illyria House",
        logoUrl: "https://example.com/illyria_logo.png",
        description: "Boutique hotel in Pretoria offering old-world charm and luxury.",
    },
    {
        id: "40",
        name: "Beverly Hills Hotel",
        logoUrl: "https://example.com/beverlyhills_logo.png",
        description: "Luxurious beachfront hotel offering elegant rooms and ocean views in Durban.",
    },
    {
        id: "41",
        name: "The Oyster Box",
        logoUrl: "https://example.com/oysterbox_logo.png",
        description: "Iconic hotel in Umhlanga, renowned for its stunning location and colonial charm.",
    },
    {
        id: "42",
        name: "Hotel Adlon Kempinski Berlin",
        logoUrl: "https://example.com/adlonkempinski_logo.png",
        description: "Historic luxury hotel near Berlin's Brandenburg Gate.",
    },
    {
        id: "43",
        name: "Sofitel Munich Bayerpost",
        logoUrl: "https://example.com/sofitelbayerpost_logo.png",
        description: "Luxury hotel combining historical architecture with modern elegance in Munich.",
    },
    {
        id: "44",
        name: "Hotel de Crillon, A Rosewood Hotel",
        logoUrl: "https://example.com/crillon_logo.png",
        description: "One of the oldest luxury hotels in Paris, located on Place de la Concorde.",
    },
    {
        id: "45",
        name: "Le Bristol Paris",
        logoUrl: "https://example.com/lebristol_logo.png",
        description: "Elegant hotel offering luxurious accommodations and Michelin-starred dining in Paris.",
    },
    {
        id: "46",
        name: "The Westin Paris - Vendôme",
        logoUrl: "https://example.com/westinparis_logo.png",
        description: "Upscale hotel with stunning views of the Tuileries Garden and the Eiffel Tower.",
    },
    {
        id: "47",
        name: "Hotel Lutetia",
        logoUrl: "https://example.com/lutetia_logo.png",
        description: "Historic hotel on the Left Bank, blending Art Deco design with contemporary luxury.",
    },
    {
        id: "48",
        name: "Steigenberger Hotel Hamburg",
        logoUrl: "https://example.com/steigenberger_logo.png",
        description: "Luxurious hotel situated along the Alsterfleet canal in Hamburg.",
    },
    {
        id: "49",
        name: "Le Pigalle Hotel",
        logoUrl: "https://example.com/lepigalle_logo.png",
        description: "Chic boutique hotel in the vibrant Pigalle district of Paris.",
    },
    {
        id: "50",
        name: "Hotel Bayerischer Hof",
        logoUrl: "https://example.com/bayerischerhof_logo.png",
        description: "Renowned luxury hotel in the heart of Munich, known for its historic charm.",
    },
    {
        id: "51",
        name: "Hotel Montaigne",
        logoUrl: "https://example.com/montaigne_logo.png",
        description: "Boutique hotel offering elegant accommodations near the Eiffel Tower in Paris.",
    },
];

export const places: IPlace[] = [
    {
        id: '1',
        name: "Motley Crew: Waterkant",
        description: "CrossFit and personal training in the heart of Waterkant.",
        category: "health",
        companyId: "1",
        address: "45 Waterkant St, Cape Town, 8001",
        coordinates: {
            lat: -33.918861,
            lon: 18.419372,
        },
    },
    {
        id: '2',
        name: "Motley Crew: Atlantic Seaboard",
        description: "Premium fitness classes with stunning views of the Atlantic.",
        category: "health",
        companyId: "1",
        address: "305 Main Rd, Sea Point, Cape Town, 8060",
        coordinates: {
            lat: -33.925839,
            lon: 18.387222,
        },
    },
    {
        id: '3',
        name: "Yoga Life: Gardens",
        description: "Serene yoga studio offering a variety of classes in Gardens.",
        category: "health",
        companyId: "2",
        address: "14 Kloof St, Gardens, Cape Town, 8001",
        coordinates: {
            lat: -33.930500,
            lon: 18.411000,
        },
    },
    {
        id: '4',
        name: "Roark Gyms: District Six",
        description: "High-intensity training and coaching in the vibrant District Six.",
        category: "health",
        companyId: "3",
        address: "65 Canterbury St, District Six, Cape Town, 8001",
        coordinates: {
            lat: -33.930614,
            lon: 18.426292,
        },
    },
    {
        id: '5',
        name: "DO Martial Arts: Sea Point",
        description: "Martial arts training with a focus on Muay Thai and BJJ in Sea Point.",
        category: "health",
        companyId: "4",
        address: "100 Regent Rd, Sea Point, Cape Town, 8060",
        coordinates: {
            lat: -33.916210,
            lon: 18.387110,
        },
    },
    {
        id: '6',
        name: "Motley Crew: City Bowl",
        description: "Fitness classes and personal training in the City Bowl area.",
        category: "health",
        companyId: "1",
        address: "23 Loop St, Cape Town City Centre, Cape Town, 8000",
        coordinates: {
            lat: -33.923241,
            lon: 18.418798,
        },
    },
    {
        id: '7',
        name: "Yoga Life: V&A Waterfront",
        description: "Peaceful yoga sessions in the iconic V&A Waterfront.",
        category: "health",
        companyId: "2",
        address: "19 Dock Rd, V&A Waterfront, Cape Town, 8001",
        coordinates: {
            lat: -33.907280,
            lon: 18.420980,
        },
    },
    {
        id: '3',
        name: "Roark Gyms: Claremont",
        description: "Intensive workouts and personalized training in Claremont.",
        category: "health",
        companyId: "3",
        address: "56 Main Rd, Claremont, Cape Town, 7708",
        coordinates: {
            lat: -33.980483,
            lon: 18.465523,
        },
    },
    {
        id: '8',
        name: "DO Martial Arts: Green Point",
        description: "Martial arts studio offering a variety of classes in Green Point.",
        category: "health",
        companyId: "4",
        address: "25 Somerset Rd, Green Point, Cape Town, 8005",
        coordinates: {
            lat: -33.909544,
            lon: 18.410557,
        },
    },
    {
        id: '9',
        name: "Motley Crew: Woodstock",
        description: "A dynamic fitness studio in the creative Woodstock area.",
        category: "health",
        companyId: "1",
        address: "66 Albert Rd, Woodstock, Cape Town, 7915",
        coordinates: {
            lat: -33.930257,
            lon: 18.446058,
        },
    },
    {
        id: '10',
        name: "Yoga Life: Atlantic Seaboard",
        description: "Sunset yoga sessions with ocean views on the Atlantic Seaboard.",
        category: "health",
        companyId: "2",
        address: "50 Victoria Rd, Camps Bay, Cape Town, 8040",
        coordinates: {
            lat: -33.951074,
            lon: 18.376151,
        },
    },
    {
        id: '11',
        name: "Roark Gyms: Rondebosch",
        description: "Strength and conditioning workouts in Rondebosch.",
        category: "health",
        companyId: "3",
        address: "89 Main Rd, Rondebosch, Cape Town, 7700",
        coordinates: {
            lat: -33.961001,
            lon: 18.476839,
        },
    },
    {
        id: '12',
        name: "DO Martial Arts: Gardens",
        description: "Martial arts and self-defense classes in the heart of Gardens.",
        category: "health",
        companyId: "4",
        address: "78 Kloof St, Gardens, Cape Town, 8001",
        coordinates: {
            lat: -33.931168,
            lon: 18.406880,
        },
    },
    {
        id: '13',
        name: "Motley Crew: Observatory",
        description: "Innovative fitness training in the trendy Observatory area.",
        category: "health",
        companyId: "1",
        address: "127 Lower Main Rd, Observatory, Cape Town, 7925",
        coordinates: {
            lat: -33.937292,
            lon: 18.468364,
        },
    },
    {
        id: '14',
        name: "Yoga Life: Newlands",
        description: "Relaxing yoga classes in the lush surroundings of Newlands.",
        category: "health",
        companyId: "2",
        address: "22 Dean St, Newlands, Cape Town, 7700",
        coordinates: {
            lat: -33.970703,
            lon: 18.464872,
        },
    },
    {
        id: '15',
        name: "Roark Gyms: Newlands",
        description: "High-performance fitness training in Newlands.",
        category: "health",
        companyId: "3",
        address: "12 Kildare Rd, Newlands, Cape Town, 7700",
        coordinates: {
            lat: -33.971801,
            lon: 18.464641,
        },
    },
    {
        id: '16',
        name: "DO Martial Arts: Woodstock",
        description: "Martial arts classes focusing on Muay Thai in Woodstock.",
        category: "health",
        companyId: "4",
        address: "215 Victoria Rd, Woodstock, Cape Town, 7915",
        coordinates: {
            lat: -33.927488,
            lon: 18.452750,
        },
    },
    {
        id: '17',
        name: "Motley Crew: Camps Bay",
        description: "Beachfront fitness studio in Camps Bay offering various classes.",
        category: "health",
        companyId: "1",
        address: "91 Victoria Rd, Camps Bay, Cape Town, 8005",
        coordinates: {
            lat: -33.951925,
            lon: 18.378825,
        },
    },
    {
        id: '18',
        name: "Yoga Life: Sea Point",
        description: "Yoga studio with a calming atmosphere in Sea Point.",
        category: "health",
        companyId: "2",
        address: "150 Main Rd, Sea Point, Cape Town, 8005",
        coordinates: {
            lat: -33.915140,
            lon: 18.392001,
        },
    },
    {
        id: '19',
        name: "Roark Gyms: Cape Town CBD",
        description: "Intensive fitness training in the bustling Cape Town CBD.",
        category: "health",
        companyId: "3",
        address: "100 Bree St, Cape Town City Centre, Cape Town, 8000",
        coordinates: {
            lat: -33.921302,
            lon: 18.419218,
        },
    },
    {
        id: '20',
        name: "DO Martial Arts: Claremont",
        description: "Martial arts training for all skill levels in Claremont.",
        category: "health",
        companyId: "4",
        address: "120 Imam Haron Rd, Claremont, Cape Town, 7708",
        coordinates: {
            lat: -33.973165,
            lon: 18.481620,
        },
    },

    {
        id: "21",
        name: "McDonald's: Cape Town CBD",
        description: "Fast food restaurant in the heart of Cape Town.",
        category: "food",
        companyId: "5",
        address: "Cnr Long St & Riebeek St, Cape Town, 8000",
        coordinates: {
            lat: -33.921509,
            lon: 18.421392,
        },
    },
    {
        id: "22",
        name: "KFC: Sea Point",
        description: "Popular fast food chain specializing in fried chicken.",
        category: "food",
        companyId: "6",
        address: "270 Main Rd, Sea Point, Cape Town, 8005",
        coordinates: {
            lat: -33.917646,
            lon: 18.393672,
        },
    },
    {
        id: "23",
        name: "Nando's: V&A Waterfront",
        description: "Portuguese-inspired flame-grilled chicken.",
        category: "food",
        companyId: "7",
        address: "Shop 7219, Victoria Wharf, V&A Waterfront, Cape Town, 8002",
        coordinates: {
            lat: -33.907987,
            lon: 18.419438,
        },
    },
    {
        id: "24",
        name: "The Test Kitchen",
        description: "Fine dining restaurant offering contemporary dishes.",
        category: "food",
        companyId: "8",
        address: "375 Albert Rd, Woodstock, Cape Town, 7925",
        coordinates: {
            lat: -33.927039,
            lon: 18.447759,
        },
    },
    {
        id: "25",
        name: "La Colombe",
        description: "Award-winning restaurant with a French-Asian fusion menu.",
        category: "food",
        companyId: "9",
        address: "Silvermist Wine Estate, Constantia Main Rd, Constantia, Cape Town, 7806",
        coordinates: {
            lat: -34.024775,
            lon: 18.406212,
        },
    },
    {
        id: "26",
        name: "Marble Restaurant",
        description: "Contemporary grill restaurant in Johannesburg.",
        category: "food",
        companyId: "10",
        address: "19 Keyes Ave, Rosebank, Johannesburg, 2196",
        coordinates: {
            lat: -26.146619,
            lon: 28.034644,
        },
    },
    {
        id: "27",
        name: "Wolfgat",
        description: "Unique dining experience with local ingredients.",
        category: "food",
        companyId: "11",
        address: "10 Sampson St, Paternoster, 7381",
        coordinates: {
            lat: -32.810947,
            lon: 17.889503,
        },
    },
    {
        id: "28",
        name: "DW Eleven-13",
        description: "Modern fine dining restaurant in Johannesburg.",
        category: "food",
        companyId: "12",
        address: "Dunkeld West Shopping Centre, Jan Smuts Ave, Johannesburg, 2196",
        coordinates: {
            lat: -26.136044,
            lon: 28.033943,
        },
    },
    {
        id: "29",
        name: "Restaurant Mosaic",
        description: "Celebrated restaurant with a focus on seasonal ingredients.",
        category: "food",
        companyId: "13",
        address: "The Orient, Crocodile River Valley, Elandsfontein, Pretoria, 0039",
        coordinates: {
            lat: -25.814154,
            lon: 27.947834,
        },
    },
    {
        id: "30",
        name: "Lucky Bean",
        description: "Laid-back restaurant offering eclectic global dishes.",
        category: "food",
        companyId: "14",
        address: "16 7th St, Melville, Johannesburg, 2092",
        coordinates: {
            lat: -26.178753,
            lon: 28.008131,
        },
    },
    {
        id: "31",
        name: "Ile Maurice",
        description: "Elegant French-inspired dining with Mauritian influence.",
        category: "food",
        companyId: "15",
        address: "9 McCausland Crescent, Umhlanga, Durban, 4320",
        coordinates: {
            lat: -29.726291,
            lon: 31.084682,
        },
    },
    {
        id: "32",
        name: "The Chairman",
        description: "Jazz lounge and restaurant in Durban.",
        category: "food",
        companyId: "16",
        address: "146 Mahatma Gandhi Rd, Point, Durban, 4001",
        coordinates: {
            lat: -29.871686,
            lon: 31.041444,
        },
    },
    {
        id: "33",
        name: "McDonald's: Berlin",
        description: "International fast food chain offering burgers, fries, and more.",
        category: "food",
        companyId: "5",
        address: "Kurfürstendamm 224, 10719 Berlin, Germany",
        coordinates: {
            lat: 52.503238,
            lon: 13.332879,
        },
    },
    {
        id: "34",
        name: "Burgermeister",
        description: "Popular burger joint in Berlin.",
        category: "food",
        companyId: "17",
        address: "Oberbaumstraße 8, 10997 Berlin, Germany",
        coordinates: {
            lat: 52.500742,
            lon: 13.448852,
        },
    },
    {
        id: "35",
        name: "Le Jules Verne",
        description: "Gourmet restaurant located in the Eiffel Tower.",
        category: "food",
        companyId: "18",
        address: "Champ de Mars, 75007 Paris, France",
        coordinates: {
            lat: 48.858370,
            lon: 2.294481,
        },
    },
    {
        id: "36",
        name: "Café de Flore",
        description: "Historic Parisian café offering classic French cuisine.",
        category: "food",
        companyId: "19",
        address: "172 Boulevard Saint-Germain, 75006 Paris, France",
        coordinates: {
            lat: 48.854321,
            lon: 2.332118,
        },
    },
    {
        id: "37",
        name: "Chez L'Ami Jean",
        description: "Traditional Basque cuisine in a cozy setting.",
        category: "food",
        companyId: "20",
        address: "27 Rue Malar, 75007 Paris, France",
        coordinates: {
            lat: 48.858569,
            lon: 2.306919,
        },
    },
    {
        id: "38",
        name: "Au Pied de Cochon",
        description: "Classic French bistro open 24/7.",
        category: "food",
        companyId: "21",
        address: "6 Rue Coquillière, 75001 Paris, France",
        coordinates: {
            lat: 48.862566,
            lon: 2.343339,
        },
    },
    {
        id: "39",
        name: "Burgertory",
        description: "Specialty burger restaurant in Pretoria.",
        category: "food",
        companyId: "22",
        address: "Shop 10, The Village, 16th St, Hazelwood, Pretoria, 0081",
        coordinates: {
            lat: -25.778835,
            lon: 28.268366,
        },
    },
    {
        id: "40",
        name: "Moo Moo Wine Bar & Grill",
        description: "Steakhouse and wine bar offering a relaxed atmosphere.",
        category: "food",
        companyId: "23",
        address: "Atterbury Rd & Charles St, Menlo Park, Pretoria, 0081",
        coordinates: {
            lat: -25.773526,
            lon: 28.261460,
        },
    },
    {
        id: "41",
        name: "Shell: Cape Town CBD",
        description: "Well-located petrol station in the heart of Cape Town.",
        category: "service_station",
        companyId: "24",
        address: "Cnr Buitengracht St & Riebeek St, Cape Town, 8000",
        coordinates: {
            lat: -33.919063,
            lon: 18.419441,
        },
    },
    {
        id: "42",
        name: "Engen: Sea Point",
        description: "24-hour service station with a convenience store.",
        category: "service_station",
        companyId: "25",
        address: "238 Main Rd, Sea Point, Cape Town, 8005",
        coordinates: {
            lat: -33.919304,
            lon: 18.387507,
        },
    },
    {
        id: "43",
        name: "BP: V&A Waterfront",
        description: "Modern fuel station with easy access to the waterfront.",
        category: "service_station",
        companyId: "26",
        address: "Breakwater Blvd, V&A Waterfront, Cape Town, 8001",
        coordinates: {
            lat: -33.906473,
            lon: 18.421995,
        },
    },
    {
        id: "44",
        name: "Total: Constantia",
        description: "Fuel station surrounded by the scenic Constantia area.",
        category: "service_station",
        companyId: "27",
        address: "Constantia Main Rd, Constantia, Cape Town, 7806",
        coordinates: {
            lat: -34.016385,
            lon: 18.416678,
        },
    },
    {
        id: "45",
        name: "Caltex: Claremont",
        description: "Conveniently located service station in Claremont.",
        category: "service_station",
        companyId: "28",
        address: "Main Rd, Claremont, Cape Town, 7708",
        coordinates: {
            lat: -33.978979,
            lon: 18.465609,
        },
    },
    {
        id: "46",
        name: "Shell: Rosebank",
        description: "24-hour fuel station in the bustling Rosebank area.",
        category: "service_station",
        companyId: "24",
        address: "Oxford Rd, Rosebank, Johannesburg, 2196",
        coordinates: {
            lat: -26.145361,
            lon: 28.036779,
        },
    },
    {
        id: "47",
        name: "Total: Sandton",
        description: "Petrol station in the upscale area of Sandton.",
        category: "service_station",
        companyId: "27",
        address: "Cnr Rivonia Rd & Sandton Dr, Sandton, Johannesburg, 2196",
        coordinates: {
            lat: -26.105856,
            lon: 28.054138,
        },
    },
    {
        id: "48",
        name: "BP: Melville",
        description: "Fuel station in the trendy suburb of Melville.",
        category: "service_station",
        companyId: "26",
        address: "7th St, Melville, Johannesburg, 2092",
        coordinates: {
            lat: -26.179554,
            lon: 28.008740,
        },
    },
    {
        id: "49",
        name: "Engen: Menlo Park",
        description: "Well-equipped service station in Menlo Park.",
        category: "service_station",
        companyId: "25",
        address: "Atterbury Rd, Menlo Park, Pretoria, 0081",
        coordinates: {
            lat: -25.773007,
            lon: 28.261378,
        },
    },
    {
        id: "50",
        name: "Sasol: Hatfield",
        description: "Modern petrol station in the heart of Hatfield.",
        category: "service_station",
        companyId: "29",
        address: "Burnett St, Hatfield, Pretoria, 0083",
        coordinates: {
            lat: -25.748342,
            lon: 28.241078,
        },
    },
    {
        id: "51",
        name: "Shell: Umhlanga",
        description: "Service station located in the vibrant Umhlanga area.",
        category: "service_station",
        companyId: "24",
        address: "McCausland Crescent, Umhlanga, Durban, 4320",
        coordinates: {
            lat: -29.727741,
            lon: 31.085502,
        },
    },
    {
        id: "52",
        name: "Total: Durban North",
        description: "Petrol station with a car wash and convenience store.",
        category: "service_station",
        companyId: "27",
        address: "Kenneth Kaunda Rd, Durban North, Durban, 4051",
        coordinates: {
            lat: -29.792061,
            lon: 31.031539,
        },
    },
    {
        id: "53",
        name: "Aral: Berlin",
        description: "Popular service station brand in Germany.",
        category: "service_station",
        companyId: "30",
        address: "Kurfürstendamm 22, 10719 Berlin, Germany",
        coordinates: {
            lat: 52.502358,
            lon: 13.334082,
        },
    },
    {
        id: "54",
        name: "Esso: Hamburg",
        description: "Convenient petrol station in Hamburg.",
        category: "service_station",
        companyId: "31",
        address: "Reeperbahn 153, 20359 Hamburg, Germany",
        coordinates: {
            lat: 53.551084,
            lon: 9.961229,
        },
    },
    {
        id: "55",
        name: "Total: Paris",
        description: "Reliable service station in central Paris.",
        category: "service_station",
        companyId: "27",
        address: "Avenue des Champs-Élysées, 75008 Paris, France",
        coordinates: {
            lat: 48.870017,
            lon: 2.307538,
        },
    },
    {
        id: "56",
        name: "Shell: Marseille",
        description: "Petrol station near the port of Marseille.",
        category: "service_station",
        companyId: "24",
        address: "Avenue du Prado, 13008 Marseille, France",
        coordinates: {
            lat: 43.273732,
            lon: 5.383475,
        },
    },
    {
        id: "57",
        name: "BP: Durban Central",
        description: "Central service station with a range of amenities.",
        category: "service_station",
        companyId: "26",
        address: "Smith St, Durban Central, Durban, 4001",
        coordinates: {
            lat: -29.857897,
            lon: 31.022523,
        },
    },
    {
        id: "58",
        name: "Total: Rosebank",
        description: "Petrol station offering quick and efficient service.",
        category: "service_station",
        companyId: "27",
        address: "Jan Smuts Ave, Rosebank, Johannesburg, 2196",
        coordinates: {
            lat: -26.144417,
            lon: 28.033508,
        },
    },
    {
        id: "59",
        name: "Engen: Rondebosch",
        description: "Convenient petrol station in Rondebosch, Cape Town.",
        category: "service_station",
        companyId: "25",
        address: "Main Rd, Rondebosch, Cape Town, 7700",
        coordinates: {
            lat: -33.958324,
            lon: 18.476985,
        },
    },
    {
        id: "60",
        name: "Sasol: Centurion",
        description: "Petrol station offering fuel and convenience store.",
        category: "service_station",
        companyId: "29",
        address: "John Vorster Dr, Centurion, Pretoria, 0157",
        coordinates: {
            lat: -25.865551,
            lon: 28.189017,
        },
    },
    {
        id: "61",
        name: "The Table Bay Hotel",
        description: "Luxury hotel located at the V&A Waterfront in Cape Town.",
        category: "hotel",
        companyId: "32",
        address: "Quay 6, Victoria & Alfred Waterfront, Cape Town, 8002",
        coordinates: {
            lat: -33.906851,
            lon: 18.420857,
        },
    },
    {
        id: "62",
        name: "One&Only Cape Town",
        description: "High-end hotel with stunning views of Table Mountain.",
        category: "hotel",
        companyId: "33",
        address: "Dock Rd, Victoria & Alfred Waterfront, Cape Town, 8001",
        coordinates: {
            lat: -33.907481,
            lon: 18.417396,
        },
    },
    {
        id: "63",
        name: "Belmond Mount Nelson Hotel",
        description: "Historic luxury hotel in the heart of Cape Town.",
        category: "hotel",
        companyId: "34",
        address: "76 Orange St, Gardens, Cape Town, 8001",
        coordinates: {
            lat: -33.933972,
            lon: 18.413681,
        },
    },
    {
        id: "64",
        name: "Camps Bay Retreat",
        description: "Luxury boutique hotel with breathtaking ocean views.",
        category: "guest_house",
        companyId: "35",
        address: "7 Chilworth Rd, Camps Bay, Cape Town, 8005",
        coordinates: {
            lat: -33.952480,
            lon: 18.379925,
        },
    },
    {
        id: "65",
        name: "Radisson Blu Hotel Sandton",
        description: "Upscale hotel in the heart of Johannesburg’s business district.",
        category: "hotel",
        companyId: "36",
        address: "Rivonia Rd & Daisy St, Sandton, Johannesburg, 2196",
        coordinates: {
            lat: -26.104472,
            lon: 28.055574,
        },
    },
    {
        id: "66",
        name: "The Saxon Hotel, Villas & Spa",
        description: "Luxury hotel and spa offering exclusivity and elegance.",
        category: "hotel",
        companyId: "37",
        address: "36 Saxon Rd, Sandhurst, Johannesburg, 2196",
        coordinates: {
            lat: -26.126412,
            lon: 28.037741,
        },
    },
    {
        id: "67",
        name: "Protea Hotel Fire & Ice! by Marriott Pretoria Menlyn",
        description: "Trendy and modern hotel in Menlyn, Pretoria.",
        category: "hotel",
        companyId: "38",
        address: "213 Thys St, Menlyn, Pretoria, 0181",
        coordinates: {
            lat: -25.781408,
            lon: 28.276646,
        },
    },
    {
        id: "68",
        name: "Illyria House",
        description: "Elegant boutique hotel in the heart of Pretoria.",
        category: "guest_house",
        companyId: "39",
        address: "327 Bourke St, Muckleneuk, Pretoria, 0002",
        coordinates: {
            lat: -25.760106,
            lon: 28.200544,
        },
    },
    {
        id: "69",
        name: "Beverly Hills Hotel",
        description: "Luxurious beachfront hotel in Umhlanga Rocks, Durban.",
        category: "hotel",
        companyId: "40",
        address: "54 Lighthouse Rd, Umhlanga Rocks, Durban, 4320",
        coordinates: {
            lat: -29.728735,
            lon: 31.085688,
        },
    },
    {
        id: "70",
        name: "The Oyster Box",
        description: "Elegant hotel with stunning views of the Indian Ocean.",
        category: "hotel",
        companyId: "41",
        address: "2 Lighthouse Rd, Umhlanga Rocks, Durban, 4320",
        coordinates: {
            lat: -29.727352,
            lon: 31.085993,
        },
    },
    {
        id: "71",
        name: "Hotel Adlon Kempinski Berlin",
        description: "Iconic luxury hotel near the Brandenburg Gate.",
        category: "hotel",
        companyId: "42",
        address: "Unter den Linden 77, 10117 Berlin, Germany",
        coordinates: {
            lat: 52.516288,
            lon: 13.377687,
        },
    },
    {
        id: "72",
        name: "Sofitel Munich Bayerpost",
        description: "Luxury hotel in a historic building in central Munich.",
        category: "hotel",
        companyId: "43",
        address: "Bayerstrasse 12, 80335 Munich, Germany",
        coordinates: {
            lat: 48.139126,
            lon: 11.558454,
        },
    },
    {
        id: "73",
        name: "Hotel de Crillon, A Rosewood Hotel",
        description: "Historic luxury hotel located on Place de la Concorde.",
        category: "hotel",
        companyId: "44",
        address: "10 Place de la Concorde, 75008 Paris, France",
        coordinates: {
            lat: 48.868595,
            lon: 2.321356,
        },
    },
    {
        id: "74",
        name: "Le Bristol Paris",
        description: "Elegant luxury hotel in the heart of Paris.",
        category: "hotel",
        companyId: "45",
        address: "112 Rue du Faubourg Saint-Honoré, 75008 Paris, France",
        coordinates: {
            lat: 48.871667,
            lon: 2.316139,
        },
    },
    {
        id: "75",
        name: "The Westin Paris - Vendôme",
        description: "Luxurious hotel with stunning views of the Eiffel Tower.",
        category: "hotel",
        companyId: "46",
        address: "3 Rue de Castiglione, 75001 Paris, France",
        coordinates: {
            lat: 48.865470,
            lon: 2.328017,
        },
    },
    {
        id: "76",
        name: "Hotel Lutetia",
        description: "Historic luxury hotel on the Left Bank of Paris.",
        category: "hotel",
        companyId: "47",
        address: "45 Boulevard Raspail, 75006 Paris, France",
        coordinates: {
            lat: 48.851777,
            lon: 2.324144,
        },
    },
    {
        id: "77",
        name: "Steigenberger Hotel Hamburg",
        description: "Luxurious hotel located on the Alsterfleet canal.",
        category: "hotel",
        companyId: "48",
        address: "Heiligengeistbrücke 4, 20459 Hamburg, Germany",
        coordinates: {
            lat: 53.550444,
            lon: 9.988699,
        },
    },
    {
        id: "78",
        name: "Le Pigalle Hotel",
        description: "Chic boutique hotel located in the vibrant Pigalle area.",
        category: "guest_house",
        companyId: "49",
        address: "9 Rue Frochot, 75009 Paris, France",
        coordinates: {
            lat: 48.882640,
            lon: 2.336533,
        },
    },
    {
        id: "79",
        name: "Hotel Bayerischer Hof",
        description: "Historic luxury hotel in the heart of Munich.",
        category: "hotel",
        companyId: "50",
        address: "Promenadeplatz 2-6, 80333 Munich, Germany",
        coordinates: {
            lat: 48.141476,
            lon: 11.570049,
        },
    },
    {
        id: "80",
        name: "Hotel Montaigne",
        description: "Charming boutique hotel near the Eiffel Tower.",
        category: "guest_house",
        companyId: "51",
        address: "6 Avenue Montaigne, 75008 Paris, France",
        coordinates: {
            lat: 48.866711,
            lon: 2.303940,
        },
    },
];
