name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Frontend
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID_FRONTEND: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd src/frontend/dashboard
          vercel --prod --token=$VERCEL_TOKEN --scope $VERCEL_ORG_ID

      - name: Deploy API Gateway
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID_GATEWAY: ${{ secrets.VERCEL_PROJECT_ID_GATEWAY }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd src/backend/api/gateway
          vercel --prod --token=$VERCEL_TOKEN --scope $VERCEL_ORG_ID

      # - name: Deploy Auth Service
      #   env:
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID_AUTH: ${{ secrets.VERCEL_PROJECT_ID_AUTH }}
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #   run: |
      #     cd src/services/auth
      #     vercel --prod --token=$VERCEL_TOKEN --scope $VERCEL_ORG_ID

      - name: Deploy Transactions Service
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID_TRANSACTIONS: ${{ secrets.VERCEL_PROJECT_ID_TRANSACTIONS }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd src/services/transactions
          vercel --prod --token=$VERCEL_TOKEN --scope $VERCEL_ORG_ID

      # - name: Deploy Rates Service
      #   env:
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID_RATES: ${{ secrets.VERCEL_PROJECT_ID_RATES }}
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #   run: |
      #     cd src/services/rates
      #     vercel --prod --token=$VERCEL_TOKEN --scope $VERCEL_ORG_ID
