name: Deploy Nexidus

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Deploy Dashboard
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd src/frontend/dashboard
          rm -rf node_modules yarn.lock
          yarn cache clean
          yarn install --frozen-lockfile
          yarn build
          vercel --prod --yes --token=$VERCEL_TOKEN

  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Deploy API Gateway
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd src/api/gateway
          rm -rf node_modules yarn.lock
          yarn cache clean
          yarn install --frozen-lockfile
          yarn build
          vercel --prod --yes --token=$VERCEL_TOKEN

  # deploy-transactions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Install Vercel CLI
  #       run: yarn global add vercel
  #     - name: Deploy Transactions Service
  #       env:
  #         VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  #       run: |
  #         cd src/services/transactions
  #         rm -rf node_modules yarn.lock
  #         yarn cache clean
  #         yarn install --frozen-lockfile
  #         yarn build
  #         vercel deploy --prod --token=$VERCEL_TOKEN
