name: Deploy Nexidus

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy Dashboard
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd src/frontend/dashboard
          npm install
          npm run build
          vercel deploy --prod --token=$VERCEL_TOKEN

  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy API Gateway
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd src/api/gateway
          npm install
          npm run build
          vercel deploy --prod --token=$VERCEL_TOKEN

  # deploy-transactions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Install Vercel CLI
  #       run: npm install -g vercel
  #     - name: Deploy Transactions Service
  #       env:
  #         VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  #       run: |
  #         cd src/services/transactions
  #         npm install
  #         npm run build
  #         vercel deploy --prod --token=$VERCEL_TOKEN
